### ISSUE TITLE
Has an undeclared runtime dependency on setuptools.

### ISSUE THREAD

**Issue by drj11** [pwaller/__autoversion__#1]
If one is devious enough to try and use `__autoversion__` without having `setuptools` installed, it won't work. That dependency isn't declared in `setup.py` which, in the absence of `requirements.txt`, is where I would expect to find it.

```
drj$ virtualenv .
New python executable in ./bin/python
Installing distribute.........................................................................................................................................................done.
Installing pip.....................done.
drj$ pwd
/home/drj/foo
drj$ ls -la
total 24
drwxrwxr-x  6 drj drj 4096 Oct 28 09:53 .
drwxr-xr-x 78 drj drj 4096 Oct 28 09:53 ..
drwxrwxr-x  2 drj drj 4096 Oct 28 09:53 bin
drwxrwxr-x  2 drj drj 4096 Oct 28 09:53 include
drwxrwxr-x  3 drj drj 4096 Oct 28 09:53 lib
drwxrwxr-x  2 drj drj 4096 Oct 28 09:53 local
drj$ . bin/activate
(foo)drj$ pip uninstall setuptools
Uninstalling distribute:
  /home/drj/foo/bin/easy_install
  /home/drj/foo/bin/easy_install-2.7
  /home/drj/foo/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg
Proceed (y/n)? y
  Successfully uninstalled distribute
(foo)drj$ git clone git@github.com:pwaller/autoversion
Cloning into 'autoversion'...
ERROR: Repository not found.
fatal: The remote end hung up unexpectedly
(foo)drj$ git clone git@github.com:pwaller/__autoversion__
Cloning into '__autoversion__'...
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 2), reused 11 (delta 2)
Receiving objects: 100% (11/11), done.
Resolving deltas: 100% (2/2), done.
(foo)drj$ cd __autoversion__/
(foo)drj$ python setup.py install --user
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying __autoversion__.py -> build/lib.linux-x86_64-2.7
warning: build_py: byte-compiling is disabled, skipping.

running install_lib
copying build/lib.linux-x86_64-2.7/__autoversion__.py -> /home/drj/.local/lib/python2.7/site-packages
warning: install_lib: byte-compiling is disabled, skipping.

running install_egg_info
Writing /home/drj/.local/lib/python2.7/site-packages/autoversion-1.1.0-py2.7.egg-info
(foo)drj$ python
Python 2.7.3 (default, Sep 26 2013, 20:03:06) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import __autoversion__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__autoversion__.py", line 12, in <module>
    from pkg_resources import DistributionNotFound, get_distribution, parse_version
ImportError: No module named pkg_resources
```

**Comment by pwaller** [comment]
For some reason when you filed this I had no idea how to fix it. I guess that does it:

```
    requires=["setuptools"],
```
